---
collections:
  - name: ansible.utils
  - name: ansible.posix
  - name: community.general
  - name: infra.aap_configuration
  - name: infra.aap_utilities
  - name: infra.ah_configuration
  - name: infra.ansible
  - name: infra.ansible_collections
  - name: infra.ansible_rekey_variables
  - name: infra.eda_configuration
  - name: infra.ee_ansible_collections
  - name: infra.ee_collections
  - name: infra.ee_configuration
  - name: infra.ee_rekey_variables
  - name: infra.ee_utilities
  - name: infra.osbuild