---
galaxy_info:
  author: Your Name
  description: Role to build and manage Ansible Execution Environments (EE) and Decision Environments (DE)
  company: Your Company
  
  license: license (GPL-2.0-or-later, MIT, etc)
  
  min_ansible_version: 2.12

  platforms:
    - name: EL
      versions:
        - 8
        - 9
  
  galaxy_tags:
    - ansible
    - automation
    - containers
    - execution_environments
    - decision_environments
    - podman
    - aap
    - ansible_automation_platform

dependencies: []

