---
- name: Ensure requirements.yml exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/environments/{{ current_env }}/requirements.yml"
  register: req_file

- name: Skip requirements fixes if file doesn't exist
  ansible.builtin.meta: end_play
  when: not req_file.stat.exists

- name: Check requirements.yml for problematic collections
  ansible.builtin.command:
    cmd: "grep -l '{{ item.pattern }}' {{ playbook_dir }}/environments/{{ current_env }}/requirements.yml"
  loop:
    - { pattern: 'infra\\.ansible', name: 'infra.ansible' }
    - { pattern: 'ansible\\.builtin', name: 'ansible.builtin'}
  changed_when: false
  failed_when: false
  loop_control:
    label: "{{ item.name }}"

- name: Fix infra.ansible reference in requirements.yml
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/environments/{{ current_env }}/requirements.yml"
    regexp: '(\s+)- name: infra\.ansible(\s+.*)?'
    replace: '\1- name: infra.ee_utilities\n\1- name: infra.aap_utilities'
  when: collection_checks.results | selectattr('item.name', 'eq', 'infra.ansible') | first | attr('rc') == 0
  register: infra_ansible_fixed

- name: Fix ansible.builtin reference in requirements.yml
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/environments/{{ current_env }}/requirements.yml"
    regexp: '(\s+)- name: ansible\.builtin(\s+.*)?'
    replace: '# The following line was removed as ansible.builtin is part of ansible-core and cannot be installed separately'
  when: collection_checks.results | selectattr('item.name', 'eq', 'ansible.builtin') | first | attr('rc') == 0
  register: ansible_builtin_fixed

- name: Check if cloud.vmware_ops is in conflict with cloud.common
  ansible.builtin.shell: |
    grep -q 'cloud\\.vmware_ops' "{{ playbook_dir }}/environments/{{ current_env }}/requirements.yml" && 
    grep -q 'cloud\\.common' "{{ playbook_dir }}/environments/{{ current_env }}/requirements.yml"
  register: vmware_conflict
  changed_when: false
  failed_when: false

- name: Fix cloud.vmware_ops and cloud.common conflict
  ansible.builtin.blockinfile:
    path: "{{ playbook_dir }}/environments/{{ current_env }}/requirements.yml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - VMWARE COLLECTION FIX"
    insertafter: "collections:"
    block: |
      # Temporarily disabled due to compatibility issues with cloud.common
      # - name: cloud.vmware_ops
      #   version: ">=0.3.0"
      - name: cloud.common
        version: ">=2.0.0,<3.0.0"
  when: vmware_conflict.rc == 0
  register: vmware_fixed

- name: Display collection fixes
  ansible.builtin.debug:
    msg: "Fixed {{ item.collection }} reference in requirements.yml for {{ current_env }}"
  loop:
    - { collection: "infra.ansible", changed: "{{ infra_ansible_fixed.changed | default(false) }}" }
    - { collection: "ansible.builtin", changed: "{{ ansible_builtin_fixed.changed | default(false) }}" }
    - { collection: "cloud.vmware_ops/cloud.common", changed: "{{ vmware_fixed.changed | default(false) }}" }
  when: item.changed | bool
