---
- name: Verify internet connectivity
  ansible.builtin.uri:
    url: https://google.com
    method: GET
  register: connectivity_check
  failed_when: connectivity_check.status != 200
  changed_when: false

- name: Fail if no internet connection is detected
  ansible.builtin.fail:
    msg: "No internet connection detected."
  when: connectivity_check.status != 200

- name: Install required packages
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: present

- name: Ensure container policy directory exists
  ansible.builtin.file:
    path: /etc/containers/policy.d
    state: directory
    mode: '0755'

- name: Create container policy file
  ansible.builtin.template:
    src: templates/container_policy.json.j2
    dest: /etc/containers/policy.d/default.json
    mode: '0644'

- name: Check if repositories exist
  ansible.builtin.stat:
    path: "{{ item.dest }}"
  register: repo_exists
  with_items: "{{ git_repos }}"

- name: Clone repositories (ignoring errors)
  block:
    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ item.item.url }}"
        dest: "{{ item.item.dest }}"
        version: 'main'
        clone: true
        update: true
        force: true
      when: not item.stat.exists
      with_items: "{{ repo_exists.results }}"
  rescue:
    - name: Display repository clone failure
      ansible.builtin.debug:
        msg: "Failed to clone repository {{ item.item.url }}. Continuing with playbook..."
      with_items: "{{ repo_exists.results }}"

- name: Install required collections
  ansible.builtin.command:
    cmd: ansible-galaxy collection install community.general
  changed_when: false
