---
- name: Verify internet connectivity  
  ansible.builtin.uri:
    url: https://google.com
    method: GET
    register: connectivity_check
    failed_when: connectivity_check.status != 200  
    changed_when: false
        
- name: Install required packages
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: latest
    tags: [setup, packages]
      
- name: Upgrade system packages
  ansible.builtin.dnf:
      name: '*'
      state: latest

- name: Check for required packages
  ansible.builtin.package:
    name:
      - python3-pip
      - ansible-core
      - podman
      - git
    state: present
  become: true

- name: Verify podman is running
  ansible.builtin.service:
    name: podman
    state: started
  become: true

- name: Verify buildah is available
  ansible.builtin.command:
    cmd: buildah --version
  changed_when: false
  register: buildah_check
  failed_when: buildah_check.rc != 0