---
collections:
  - name: ansible.utils
    version: ">=2.10.0"
  - name: ansible.posix
    version: ">=1.5.4"
  - name: community.general
    version: ">=7.0.0"
  - name: crowdstrike.falcon
    version: ">=4.7.2"