---
# requirements.yml
# This requirements file lists all the collections from
# the red hat ansible automation hub that we want installed on Tower

collections:
  - a10.acos_cli
  - amazon.aws
  - ansible.controller
  - ansible.netcommon
  - ansible.network
  - ansible.posix
  - ansible.security
  - ansible.tower
  - ansible.utils
  - ansible.windows
  - arista.avd
  - arista.cvp
  - arista.eos
  - arubanetworks.aoscx
  - azure.azcollection
  - check_point.gaia
  - chocolatey.chocolatey
  - cisco.aci
  - cisco.asa
  - cisco.dnac
  - cisco.ios
  - cisco.iosxr
  - cisco.mso
  - cisco.nae
  - cisco.nxos
  - citrix.adc
  - cloud.common
  - crowdstrike.falcon
  - cyberark.conjur
  - cyberark.pas
  - dellemc.enterprise_sonic
  - dellemc.openmanage
  - dellemc.os10
  - dellemc.os6
  - dellemc.os9
  - dellemc.powerflex
  - dellemc.powermax
  - dellemc.powerscale
  - dellemc.powerstore
  - dellemc.unity
  - dellemc.vplex
  - dynatrace_innovationlab.dynatrace_collection
  - f5networks.f5_bigip
  - f5networks.f5_modules
  - fortinet.fortios
  - frr.frr
  - google.cloud
  - hpe.ilo
  - hpe.nimble
  - hpe.oneview
  - ibm.ibm_zos_cics
  - ibm.ibm_zos_core
  - ibm.ibm_zos_ims
  - ibm.ibm_zosmf
  - ibm.ibm_zos_sysauto
  - ibm.isam
  - ibm.power_aix
  - ibm.power_hmc
  - ibm.power_ibmi
  - ibm.power_vios
  - ibm.qradar
  - ibm.spectrum_virtualize
  - infoblox.nios_modules
  - inspur.sm
  - junipernetworks.junos
  - kubernetes.core
  - logicmonitor.integration
  - microsoft.sql
  - monitorapp.monitorapp_waf
  - netapp.aws
  - netapp.azure
  - netapp.cloudmanager
  - netapp.elementsw
  - netapp.ontap
  - netapp.storagegrid
  - netapp.um_info
  - newrelic.newrelic_agents
  - nginxinc.nginx_controller
  - nginxinc.nginx_core
  - nvidia.cumulus_linux_roles
  - onepassword.connect
  - opensvc.cluster
  - openvswitch.openvswitch
  - phoenixnap.bmc
  - pureport.fabric
  - purestorage.flasharray
  - purestorage.flashblade
  - purestorage.pure1
  - redhat.insights
  - redhat.jws
  - redhat.openshift
  - redhat.redhat_csp_download
  - redhat.rhel_idm
  - redhat.rhel_system_roles
  - redhat.rhv
  - redhat.satellite
  - redhat.satellite_operations
  - rubrikinc.cdm
  - sap.rhel
  - seiko.smartcs
  - sensu.sensu_go
  - servicenow.itsm
  - splunk.es
  - tirasa.syncope
  - trendmicro.deepsec
  - vmware.alb
  - vmware.vmware_rest
  - vyos.vyos
  - wti.remote
